# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/beandog/433/ECE433-Lab7/Lab7.srcs/sources_1/ip/Clock80MHz/Clock80MHz.xci
# IP: The module: 'Clock80MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/beandog/433/ECE433-Lab7/Lab7.gen/sources_1/ip/Clock80MHz/Clock80MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/beandog/433/ECE433-Lab7/Lab7.gen/sources_1/ip/Clock80MHz/Clock80MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/beandog/433/ECE433-Lab7/Lab7.gen/sources_1/ip/Clock80MHz/Clock80MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/beandog/433/ECE433-Lab7/Lab7.srcs/sources_1/ip/Clock80MHz/Clock80MHz.xci
# IP: The module: 'Clock80MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/beandog/433/ECE433-Lab7/Lab7.gen/sources_1/ip/Clock80MHz/Clock80MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/beandog/433/ECE433-Lab7/Lab7.gen/sources_1/ip/Clock80MHz/Clock80MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/beandog/433/ECE433-Lab7/Lab7.gen/sources_1/ip/Clock80MHz/Clock80MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock80MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
