# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/beandog/433/ECE433-Lab7/final-project/finalproject.srcs/sources_1/ip/clk_wiz_50MHz/clk_wiz_50MHz.xci
# IP: The module: 'clk_wiz_50MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/beandog/433/ECE433-Lab7/final-project/finalproject.gen/sources_1/ip/clk_wiz_50MHz/clk_wiz_50MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50MHz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/beandog/433/ECE433-Lab7/final-project/finalproject.gen/sources_1/ip/clk_wiz_50MHz/clk_wiz_50MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/beandog/433/ECE433-Lab7/final-project/finalproject.gen/sources_1/ip/clk_wiz_50MHz/clk_wiz_50MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/beandog/433/ECE433-Lab7/final-project/finalproject.srcs/sources_1/ip/clk_wiz_50MHz/clk_wiz_50MHz.xci
# IP: The module: 'clk_wiz_50MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/beandog/433/ECE433-Lab7/final-project/finalproject.gen/sources_1/ip/clk_wiz_50MHz/clk_wiz_50MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/beandog/433/ECE433-Lab7/final-project/finalproject.gen/sources_1/ip/clk_wiz_50MHz/clk_wiz_50MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/beandog/433/ECE433-Lab7/final-project/finalproject.gen/sources_1/ip/clk_wiz_50MHz/clk_wiz_50MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
